language: node_js
node_js:
  - "8"
  - "6"
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
before_script:
  - npm install -g mocha
after_success:
  - npm run-script cover
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
    tags: true
